flaskblog/user/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.user.formes import (RegistrationForm, LoginForm, UpdateAccountForm,
                        ResetPasswordForm)
from flaskblog.user.utilis import  save_picture, send_reset_email
users = Blueprint('users', __name__)



@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hased_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hased_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Login Unsuccessful, Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has ben updated!', 'success')
        return redirect(url_for('account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page,per_page=5)
    return render_template('user_post.html',posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'Post'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instriuctionto reset your password')
    return render_template('reset_request.html', title='Reset Password',form=form)

@users.route("/reset_password/<token>", methods=['GET', 'Post'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hased_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')

        user.password = hased_password
        db.session.commit()
        flash('Your passord has been Update! You are now able to log in', 'success')
        return redirect(url_for('login'))
    return render_template('reset_token.html', title='Reset Password',form=form)



@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('home'))

flaskblog/web/routes.py
import queue
import threading
#########################################################
from flask import Blueprint
from flask import redirect, render_template, request, url_for

import flaskblog.web.routes
from flaskblog.forms import (Indicators, InsiderBuy,
                        Sentiement, Twitt)
from flaskblog.models import Post
from flaskblog.utility.utilities1 import inviznews
from flaskblog.utility.utilities2 import techanical_data
from flaskblog.utility.utility4 import inside_buy, market_sentiemnt
from flaskblog.utility.utility6 import twitter_sentiemnt
###########################################################
q = queue.Queue()
thread = threading.Thread(target=inviznews, args=(q,))
thread.start()
posts = q.get()

import os
template_dir = os.path.abspath('C:\\Users\\amirr\\Desktop\\html+css\\flask\\flaskblog\\web\\templates')
main = Blueprint('main', __name__, template_folder=template_dir)
#print(help(render_template))
###################################################
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page',1,type=int)
#    posts2 = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    if posts:
        posts1 = posts
        return render_template('home.html',posts1=posts1)
        #return render_template(url_for('templates',filename='home.html'),
        #posts1=posts1,posts2=posts2)
    return render_template('home.html',
                           )

@main.route('/techanical_indicators', methods=['GET', 'POST'])
def techanical_indicators():
    form = Indicators()
    name = ''
    name1 = ''
    if form.validate_on_submit():
        if form.validate_time(period=form.time_period.data,interval=form.time_interavel.data):
            ticker1 =  form.ticker.data
            period = form.period[    form.time_period.data]
            interval1 = form.interval[ form.time_interavel.data]
            bolinger = form.bolinger_band.data
            firstavg = form.sma1.data
            rsi = form.rsi.data
            secAvg = form.sma2.data
            macd = form.macd.data
            ex_avg = form.ewm1.data
            trueRange = form.trueRange.data
            fig1 = techanical_data(ticker=ticker1, period=period, movingAverageNo1=firstavg, interval=interval1, movingAverageNo2=secAvg, exponentialMovingAverage=ex_avg, plotMacd=macd
                                   , rsi=rsi, AverageTrueRange=trueRange, bolinger_band=bolinger)
            return render_template('techanical indicators.html', title='About', fig1=fig1,form=form)
        else:
            return redirect(url_for('techanical_indicators'))

    return render_template('techanical indicators.html', title='About',form=form)
############################################################



############################################################################


@main.route("/derivative", methods=['GET', 'POST'])
def derivative():
    name = None
    name1 = None
    stock = Sentiement()
    stock = Sentiement()
    if stock.validate_on_submit():
        name = stock.stock1.data
        name1 = stock.date.data
        stock = ''
        fig1 = market_sentiemnt(stock=name,user_date=name1)
        stock = Sentiement()
        return render_template('Derivative.html', fig1=fig1, stock=stock)

    elif stock.stock1.data != "":
            if stock.is_submitted():
                name = stock.stock1.data
                stock = ' '
                fig = market_sentiemnt(name)
                stock = Sentiement()
                return render_template('Derivative.html', fig=fig, stock=stock)

    return render_template('Derivative.html', stock=stock)


@main.route('/socialMedia', methods=['POST', 'GET'])
def twiterSentiemnt():
    form = Twitt()

    if form.validate_on_submit():
        name = form.number_of_search.data
        name1 = form.search.data
        form = ''
        fig1 = twitter_sentiemnt(name,name1)
        form = Twitt()

        return render_template('socialMedia.html',fig1=fig1,form=form)

    return render_template('socialMedia.html',form=form)


@main.route("/Insider's", methods=['GET', 'POST'])
def insider():
    name = ''
    form = InsiderBuy()
    if form.validate_on_submit():
        name = form.ticker.data
        name1 = form.max_result1.data

        days = form.days_Go_dic[form.days_ago.data]
        form = ''

        fig1 = inside_buy(company=name,max_result=name1,days_go=days)
        form = InsiderBuy()

        return render_template('insiders.html',form=form,fig1=fig1)

    return render_template('insiders.html',form=form)










# Define Dash app layout

# Create Flask server

flaskblog/templates/layout1.html
<!doctype html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- Latest compiled and minified CSS -->
        <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              rel="stylesheet">

<!-- Optional theme -->
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Document</title>
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout1.css') }}">
        {% if title %}
            <title>Flask Blog - {{ title }}</title>
        {% else %}
            <title>Flask Blog</title>
        {% endif %}
</head>
<body>
        <headr>
            <nav>
                <ul class="ul1">
                     <li class="warrper1" ><img src="{{url_for('static',filename='icons/' + 'home.png')}}" alt="no  content" ><a class="nav-item nav-link1" href="{{ url_for('main.home') }}"> Home</a></li>
                     <li class="warrper1" id="indc" > <img src="{{url_for('static',filename='icons/' + 'techanical.png')}}" alt="no  content" ><a class="nav-item nav-link1" href="{{ url_for('main.techanical_indicators') }}">Techanical Indicators</a></li>
                     <li class="warrper1" id="levrage"> <img src="{{url_for('static',filename='icons/' + 'hedge.png')}}" alt="no  content"> <a class="nav-item nav-link1" href="{{ url_for('main.derivative') }}">Levarge</a></li>
                     <li class="warrper1" id="inside"><img src="{{url_for('static',filename='icons/' + 'insider.png')}}" alt="no  content"><a class="nav-item nav-link1" href="{{ url_for('main.insider') }}">Insider's Buy & Sale</a></li>
                     <li class="warrper1" id="twit" ><img src="{{url_for('static',filename='icons/' + 'twiiter.png')}}" alt="no  content"><a class="nav-item nav-link1" href="{{ url_for('main.twiterSentiemnt') }}">Social Media</a></li>
                 </ul>
                 <ul class="navbar-nav">
                          {% if current_user.is_authenticated %}
                          <li class="first"><a class="nav-item nav-link" href="{{ url_for('new_post') }}">New Post</a><li>

                          <li><a class="nav-item nav-link" href="{{ url_for('account') }}">Account</a><li>

                            <li><a class="nav-item nav-link" href="{{ url_for('logout') }}">logout</a></li>

                          {% else %}
                            <li><a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a></li>
                            <li><a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a></li>
                          {% endif %}
                </ul>
            </nav>
        </headr>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
              {% for message in messages %}
                 <div id = "myAlert" class = "alert alert-warning">
                    <a href = "#" class = "close" data-dismiss = "alert">&times;</a>
                     <strong>{{message}}</strong>
                 </div>
               {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %} {% endblock %}
        <script type = "text/javascript">
           $(function(){
              $(".close").click(function(){
                 $("#myAlert").alert();
              });
           });
        </script>

           <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>